### ISSUE TITLE
Contact us page

### ISSUE THREAD

**Issue by HRITVIK25** [abhishekraoas/MCA-Alumni-Network#11]
can add the form component for contact us in react

**Comment by abhishekraoas** [comment]
Yes, you can design a modern Contact Us form. I assigned you in this issue

**Comment by HRITVIK25** [comment]
![Screenshot 2024-10-02 171131](https://github.com/user-attachments/assets/2c0a7a24-f866-4cb5-9505-75047e4352c5)
![Screenshot 2024-10-02 171157](https://github.com/user-attachments/assets/96b4f917-8a23-44a6-9614-03140553df48)
created a form component in react using tailwind and emailjs mails are 
Mails are being successfully received when submitted and form is reset

**Comment by HRITVIK25** [comment]
also if you do not mind i am new to open source can you kindly help me how to generate a pull request or how to submit my changes

**Comment by abhishekraoas** [comment]
> also if you do not mind i am new to open source can you kindly help me how to generate a pull request or how to submit my changes

You can watch the youtube videos

**Comment by abhishekraoas** [comment]
> ![Screenshot 2024-10-02 171131](https://private-user-images.githubusercontent.com/148693112/372847893-2c0a7a24-f866-4cb5-9505-75047e4352c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4Njk5MjQsIm5iZiI6MTcyNzg2OTYyNCwicGF0aCI6Ii8xNDg2OTMxMTIvMzcyODQ3ODkzLTJjMGE3YTI0LWY4NjYtNGNiNS05NTA1LTc1MDQ3ZTQzNTJjNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMlQxMTQ3MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNmNlNjhlZjQ5NjUwOTM5NGFjYTA5NTQ0N2NmYTc2Zjg2MTVlZTQwNWQwMzhhNTgzZjVmNDdhNWRlOGFiMzM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.aurnIVgWJvIRh3D2M3p580_b88nEIeDdi0m-XVE-0VE) ![Screenshot 2024-10-02 171157](https://private-user-images.githubusercontent.com/148693112/372847944-96b4f917-8a23-44a6-9614-03140553df48.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4Njk5MjQsIm5iZiI6MTcyNzg2OTYyNCwicGF0aCI6Ii8xNDg2OTMxMTIvMzcyODQ3OTQ0LTk2YjRmOTE3LThhMjMtNDRhNi05NjE0LTAzMTQwNTUzZGY0OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMlQxMTQ3MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YzcxNWVlMjgxZmVkNjUxYTc1M2RhZjBhMmJiZTQ2NGVkZTBhN2NhODAzM2RlZDk5YzUxZDA4MTA3NjVjNDdjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.37c949HSMjLBalhvuSzu8ryZ_LmEM2GZUZaI1wlXKwA) created a form component in react using tailwind and emailjs mails are Mails are being successfully received when submitted and form is reset

design like this 
![{E315BBD5-438F-49E9-80D1-A0242EEBD6F8}](https://github.com/user-attachments/assets/6b8d1564-07b7-4bf4-9509-953b86f82fbd)

**Comment by saimohan11** [comment]
@abhishekraoas can you assign me this task.

**Comment by abhishekraoas** [comment]
> @abhishekraoas can you assign me this task.

this task is already has been assigned

**Comment by HRITVIK25** [comment]
![Uploading Screenshot 2024-10-02 230055.png…]()

**Comment by HRITVIK25** [comment]
[
![Uploading Screenshot 2024-10-02 230055.png…]()
](url)

**Comment by HRITVIK25** [comment]
[
![Screenshot 2024-10-02 230055](https://github.com/user-attachments/assets/8afd6d2f-dda4-4ff0-b6f0-abeaf61b2135)
](url)
