### ISSUE TITLE
Enhance landing page of website my making it more interactive

### ISSUE THREAD

**Issue by Varchasavkr** [abhishekraoas/MCA-Alumni-Network#118]
Previous img looked very stagnant 

https://github.com/user-attachments/assets/ac7b0f8c-8807-4e0c-bc18-6dae38b52881

I have made these changes 

**NEW Changes** 

https://github.com/user-attachments/assets/6723b3a5-4ae9-41bb-9e58-17c20919ba19

These are the line of code added and the previous code has been left commented in case or more changes 

![image](https://github.com/user-attachments/assets/f4c411f1-bdfe-4f48-9d03-b250932b894f)

Kindly assign this to me and add label of hacktoberfest-accepted and gssoc-ext with level
THANKYOU!

**Comment by Varchasavkr** [comment]
This issue has been solved in PR #119 
Kindly merge this under hacktoberfest2024 #hacktoberfest-accepted #gssoc-ext and level

**Comment by abhishekraoas** [comment]
I already merged it
