### ISSUE TITLE
there is an issue in text input area in all sections

### ISSUE THREAD

**Issue by Varchasavkr** [abhishekraoas/MCA-Alumni-Network#124]
if we use chrome suggested input then the input textfield is taking it as text color white but if we deliberately type in input text area then it is taking normal black and this bug is in all the section of input areas

https://github.com/user-attachments/assets/c7108824-b03d-4816-bc73-9957914ebd56

as you can see in video
the suggestion is not captured by windows in screen recording but the text appearing in input area is white when I select it all in blue BUT as i type the typing is fine in black color
Kindly assign this to me 

Kindly merge this under #hacktoberfest-accepted #gssoc-ext ans level
Thankyou

**Comment by Varchasavkr** [comment]
Kindly assign this to me

**Comment by Varchasavkr** [comment]
THIS IS SOLVED IN PR #126 
kindly merge this under #hacktoberfest-accepted #gssoc-ext #level

THankyou

**Comment by abhishekraoas** [comment]
I already merged
