### ISSUE TITLE
The scroll bar of your website is not looking good and it is default which is not suited in your website.

### ISSUE THREAD

**Issue by VinayLodhi1712** [abhishekraoas/MCA-Alumni-Network#13]
The side scroll bar is not looking good on website I want to make it good UI like this below video with your website suited colour.

![scrollbar](https://github.com/user-attachments/assets/ae2b788e-aab2-4e76-ab9d-183ed9a39e5d)

https://github.com/user-attachments/assets/cbc7d36e-c58a-405e-87c4-bf7bda7940f3

Sir @abhishekraoas assign me this issue under gssoc extended and hactoberfest.

**Comment by abhishekraoas** [comment]
You can do I assigned you on this issue

**Comment by abhishekraoas** [comment]
Ya sure you can connect with me on LinkedIn

**Comment by VinayLodhi1712** [comment]
ok i will start working on this.

**Comment by VinayLodhi1712** [comment]
hello sir @abhishekraoas  can you plz add level in it so it will be help me to add PR on gssoc leaderboard, this PR is not showing there because on no level add on it
