### ISSUE TITLE
[BUG]: Landing page dimensions are incorrect.

### ISSUE THREAD

**Issue by NilanchalaPanda** [abhishekraoas/MCA-Alumni-Network#132]
- When `Join the network` button is hovered, the landing widens and a horizontal scroller appears.
- Also the social icons are misplaced because of this issue.
- I would be happy to work upon this issue and resolve the bug.

- Hacktoberfest Contributor.
- GSSOC-EXT'24 Contributor.

**Comment by abhishekraoas** [comment]
@NilanchalaPanda Look again if this issue exists then let me know

**Comment by NilanchalaPanda** [comment]
Yes, now it looking better.
