### ISSUE TITLE
Add contributors.md in readme.md

### ISSUE THREAD

**Issue by Aditijainnn** [abhishekraoas/MCA-Alumni-Network#138]
in readme add contributors
assign this to me under gssoc ext

**Comment by abhishekraoas** [comment]
Mention with proper details

**Comment by Aditijainnn** [comment]
> Mention with proper details

in readme i will add a section in which contributors profile will be displayed
also if we scroll till bottom of readme there will be a button go to top on clicking that the viewer can go straight to top of readme without scrolling

**Comment by abhishekraoas** [comment]
> > Mention with proper details
> 
> in readme i will add a section in which contributors profile will be displayed also if we scroll till bottom of readme there will be a button go to top on clicking that the viewer can go straight to top of readme without scrolling

There is no need this because the contribution profiles are already showing the right side. You can work on the other components
