### ISSUE TITLE
Contact Page and Home Page Not Responsive

### ISSUE THREAD

**Issue by simmi-verma** [abhishekraoas/MCA-Alumni-Network#154]
The contact page and home page of the application are not displaying correctly on mobile devices and smaller screens. This affects user experience and accessibility.
![Screenshot (1075)](https://github.com/user-attachments/assets/a6d9adb4-8020-4c84-a9c8-56e0a656f225)

![Screenshot (1074)](https://github.com/user-attachments/assets/d59bc1fe-b533-4ca6-9558-d2a77e141211)

I would you like to work on this .Please assign to me .

**Comment by agarwalhimanshugaya** [comment]
@simmi-verma try to work on some other issue someone is already working
