### ISSUE TITLE
Missing Contact Us Models

### ISSUE THREAD

**Issue by simmi-verma** [abhishekraoas/MCA-Alumni-Network#158]
I have identified that the models for the "Contact Us" component are currently missing from the project. This is essential for managing form data and ensuring proper functionality when users submit their messages.

**Comment by agarwalhimanshugaya** [comment]
@simmi-verma we use emailjs library for contacting us i don't think we need any models if you have any further idea comment below

**Comment by simmi-verma** [comment]
Sir, we can implement Google authentication.

**Comment by simmi-verma** [comment]
Sir, we can implement Google authentication.

**Comment by simmi-verma** [comment]
Ok
