### ISSUE TITLE
Integrating Google Login: Adding Google Authentication to Your Website

### ISSUE THREAD

**Issue by amanver45** [abhishekraoas/MCA-Alumni-Network#179]
In this project, we will implement a Google login button on a web page using Google’s OAuth 2.0 API. The Google Sign-In integration allows users to authenticate securely using their Google credentials, which improves convenience, security, and user retention.

The key steps in this project are:

Setting up Google API: Create a project in Google Developer Console, enable the OAuth API, and obtain client credentials.
HTML Structure: Design a login page with a “Sign in with Google” button.
JavaScript Integration: Use Google’s JavaScript API to manage the authentication process. When a user clicks the login button, they will be prompted to log in via their Google account.
Handling Authentication: Once the user logs in, retrieve their profile information (name, email, etc.), and handle session management.

**Comment by agarwalhimanshugaya** [comment]
@amanver45 we cannot implement this because in registeration we take lot of detail related to college and job
