### ISSUE TITLE
Improvement of Alumni Cards and ability to search and Filter

### ISSUE THREAD

**Issue by IkkiOcean** [abhishekraoas/MCA-Alumni-Network#194]
# Improvement of Alumni Cards in MCA Alumni Network Web Application

### 📝 Description
The current design and functionality of the Alumni Cards in the MCA alumni network web application need enhancement to improve accessibility and Aesthetics of it.

### 📋 Proposed Changes
- Redesign the layout of the Alumni Cards for better visibility and aesthetics.
- Add more detailed information about each alumnus, such as current position, achievements, and areas of expertise.
- Implement a filtering system to allow users to search for alumni based on various criteria (e.g., graduation year, profession).
- Ensure mobile responsiveness to improve usability on different devices.

### 🎯 Benefits
- Enhanced user experience by providing clear and organized information.
- Increased engagement among alumni, encouraging connections and networking.
- Better accessibility for users seeking specific alumni profiles.

## Current State:
<img width="1280" alt="Screenshot 2024-10-13 at 6 12 44 PM" src="https://github.com/user-attachments/assets/a8e5090b-56d6-43cd-8d21-841805d0d051">

- These cards dont look attractive and lack the correct Positioning
- Searching for specific alumni is not possible.
### 🗓️ Timeline
I will deliver it in 1 day.

**Comment by abhishekraoas** [comment]
Now you can work on it

**Comment by IkkiOcean** [comment]
@abhishekraoas 
please assign level 3 since I will changing looks of whole page and adding features like search and filter..
