### ISSUE TITLE
[BUG] Dark Mode Button Not Functioning

### ISSUE THREAD

**Issue by amanver45** [abhishekraoas/MCA-Alumni-Network#216]
Description
The dark mode toggle button is not functioning as expected. When clicked, it does not switch the website's theme to dark mode. This issue prevents users from enabling dark mode, which can negatively affect the user experience, especially for those who prefer darker themes for accessibility or aesthetic reasons.

Steps to Reproduce
Open the website.
Locate the dark mode toggle button (usually in the navigation bar or settings section).
Click the button to switch to dark mode.
Observe that the website’s theme does not change

Expected Behavior
Clicking the dark mode button should change the website’s theme to dark mode, adjusting the colors and appearance of the site accordingly.

Actual Behavior
Clicking the dark mode button has no effect on the theme. The website remains in its default (light) mode.
![Uploading Screenshot 2024-10-16 144230.png…]()

**Comment by agarwalhimanshugaya** [comment]
@amanver45 it is duplicate kindly work on other issue

**Comment by abhishekraoas** [comment]
@amanver45 now you can work on it.
