### ISSUE TITLE
Implement Password Recovery Page

### ISSUE THREAD

**Issue by saras-69** [abhishekraoas/MCA-Alumni-Network#241]
Description: Create a password recovery page that allows users to reset their passwords. This functionality is essential for improving user experience and account security.

**Comment by agarwalhimanshugaya** [comment]
@saras-69 u can work on it but how u do first explain

**Comment by saras-69** [comment]
set up a PasswordRecovery component using useState for managing email, otp, and newPassword. The UI follows a three-step flow: email input to simulate OTP sending, OTP verification, and password reset. Alerts are used to mimic sending and verifying OTPs and resetting the password, providing a basic demonstration. This approach can be expanded later with actual API integration for a complete password recovery process.
