### ISSUE TITLE
Improve styling and UI of Register as alumni page

### ISSUE THREAD

**Issue by jainaryan04** [abhishekraoas/MCA-Alumni-Network#38]
![image](https://github.com/user-attachments/assets/24f393bf-04ba-4ccc-a245-ef99ad2a841c)
The register as alumni page appears to be a basic form as of now. 

Proposed improvements - 
use a gradient as a background colour
restructure the form inputs - instead of stacking the input fields as a single column, use a table-like layout and add a image / design in the remaining screen space.
change hover effect of submit button.

@abhishekraoas please assign it to me with gssoc-extend and hacktoberfest labels.

**Comment by abhishekraoas** [comment]
@jainaryan04 You can work on it and try a design like this 
![{993091A4-833E-405A-B43A-154BA49DF360}](https://github.com/user-attachments/assets/afb800d2-7f70-4b74-ba9b-299fb602a40f)

**Comment by jainaryan04** [comment]
![image](https://github.com/user-attachments/assets/594697ef-0a5f-45cb-8c36-719e8cf75760)
how does this look ? 
@abhishekraoas

**Comment by abhishekraoas** [comment]
Looking good

**Comment by jainaryan04** [comment]
@abhishekraoas I fixed it but there are some conflicts after the new commits to the base repo.
Protected Route is used in App.jsx but it's not defined.

**Comment by abhishekraoas** [comment]
> @abhishekraoas I fixed it but there are some conflicts after the new commits to the base repo. Protected Route is used in App.jsx but it's not defined.

if you can fix this issue then do.
