### ISSUE TITLE
Add Greetings Bot

### ISSUE THREAD

**Issue by KiranBaliga** [abhishekraoas/MCA-Alumni-Network#5]
Hey 🥳 Looks like an amazing project idea! I see this repo lacks a small enhancement Github Greetings bot that sends auto messages to greet new users when they raise a PR or an issue. Let me know if you would like this level1 set up! Please assign to me if interested! (GSSoC24 Contribution)

**Comment by harish08102004** [comment]
Hey @KiranBaliga I can work on this.

**Comment by KiranBaliga** [comment]
@abhishekraoas I have raised a PR. Please add level1 and GSSoC24-Ext labels to the PR please and also the earlier ones. Thank you so much.

**Comment by Charul00** [comment]
can you please assign to me i have interest in it

**Comment by KiranBaliga** [comment]
@Charul00 The issue is already assigned to me, also raised a PR. Please checkout other bugs, issues etc. Thank you for your understanding.
