### ISSUE TITLE
FEATURE: Add a Blog page to the website 

### ISSUE THREAD

**Issue by shubhagarwal1** [abhishekraoas/MCA-Alumni-Network#52]
I propose to add a new blog page on the website where users can find a detailed tutorial on how to use the services provided by Rentalog.in.
Hey @abhishekraoas Please assign this task to me .

**Comment by abhishekraoas** [comment]
There is no need to blog page

**Comment by shubhagarwal1** [comment]
> There is no need to blog page

Is there any thing specific you are looking for improvement or any new feature request, i would love to work on it 
@abhishekraoas

**Comment by abhishekraoas** [comment]
you can work on the User cards to make more attractive design

**Comment by shubhagarwal1** [comment]
> you can work on the User cards to make more attractive design

ok, please assign the task to me, under gssoc-ext labels 
so that i can start with the implementation @abhishekraoas

**Comment by abhishekraoas** [comment]
First you have to create new issue

**Comment by shubhagarwal1** [comment]
have created a new issue please assign it to me @abhishekraoas
