### ISSUE TITLE
Refactoring Server.js file so that it can be read easily

### ISSUE THREAD

**Issue by rishyym0927** [abhishekraoas/MCA-Alumni-Network#55]
![image](https://github.com/user-attachments/assets/42a73579-b213-4bcc-a085-33576220d49a)

Hey @abhishekraoas 

As you can see the code is written in a very messed up manner and is not self explanatory in nature. I want to refactor this

Please assign it to me under gssoc ext level2

**Comment by abhishekraoas** [comment]
Now you can do.
