### ISSUE TITLE
Shifting The Entire Handler Function In Controllers

### ISSUE THREAD

**Issue by rishyym0927** [abhishekraoas/MCA-Alumni-Network#56]
![image](https://github.com/user-attachments/assets/5c0938b4-6707-450d-9bfc-a02d9a11bd9a)

Some of the handler functions are written in the route folders which should be shifted in the controllers for better readability and debugging

Assign this issue to me under gssoc ext level3

**Comment by abhishekraoas** [comment]
You can fix now

**Comment by rishyym0927** [comment]
can you add the label of level3 please

**Comment by abhishekraoas** [comment]
> can you add the label of level3 please

done✅️
