### ISSUE TITLE
Inappropriate .gitignore Files

### ISSUE THREAD

**Issue by rishyym0927** [abhishekraoas/MCA-Alumni-Network#57]
![image](https://github.com/user-attachments/assets/2c1e5961-7586-4edb-8e7c-116a0a764442)

As you can see the .gitignore files is not written completely and it should be completed to avoid any  kind of potential mistakes by pushing uncessary files to the repo

Assign this to me under gssoc ext level3

**Comment by abhishekraoas** [comment]
Fix it. I assigned you
