### ISSUE TITLE
Setting Up Nodemon For Hot Reloading 

### ISSUE THREAD

**Issue by rishyym0927** [abhishekraoas/MCA-Alumni-Network#59]
Hey @abhishekraoas 

Since its a nodejs project I want to setup a nodemon server for development purpose. Assign it to me under gssoc ext level1

**Comment by rishyym0927** [comment]
ok cool can I create issue regard the readme update as its not mentioned over there?

**Comment by abhishekraoas** [comment]
> ok cool can I create issue regard the readme update as its not mentioned over there?

Sure
