### ISSUE TITLE
Update in the model to include profile photo and also by adding few extra details

### ISSUE THREAD

**Issue by rishyym0927** [abhishekraoas/MCA-Alumni-Network#97]
Hey I can see that there is no provision for adding profile photo for users, I want to add that in the model and also to edit few things in the model as well. Thank you assign this under gssoc ext

**Comment by abhishekraoas** [comment]
I assigned you but first, you have to make sure your branch should be up to date with the main branch and there should not be any code conflict

**Comment by rishyym0927** [comment]
okay I will make sure about it
